### ISSUE TITLE
Filter numbers in text

### ISSUE THREAD

**Issue by david-feliz** [amiletti/Dataigniter#1]
Hello,
There is a problem when searching for numbers within a text: if the search begins with a number, it does not return any results because it makes an exact comparison.

The problem triggers in the instruction IF in the line 230...

> ```
> if(is_numeric($val))
> {
>   $q = " = ".$this->CI->db->escape($val)." ";
> }
> ```

To avoid this, I comment that instruction, but I imagine there will be a more elegant solution.
Could you check it?

Congratulations for the library, I really like it! :)

**Comment by amiletti** [comment]
Hi,

thank for your tip.
I' ve added a little improvement in order to add the ability to set the column type in config file.
As you can see, in the /application/config/dataigniter.php you can add the key 'ct' /\* column type */ in the column configuration.

I' ve only added 'string' and 'numeric' type, but you can add what you want in the switch at line 250

Thanks again,

**Comment by david-feliz** [comment]
Excellent!
Thank you very much!
